# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

# Get thunderloom dependencies
- task: DownloadPackage@1
  inputs:
    packageType: 'upack'
    feed: '/5f5d377c-f4e8-4587-acd2-348e71a79799'
    view: 
    definition: 'f25dc537-a23e-474d-98f3-fa5af32ce539'
    version: '0.0.1'
    downloadPath: 'frontends/dependencies/'

# Get max/vray sdks
- task: DownloadPackage@1
  inputs:
    packageType: 'upack'
    feed: '/5f5d377c-f4e8-4587-acd2-348e71a79799'
    view: 
    definition: 'db2e8b61-26ce-4d06-8201-58f9e83232c9'
    version: '0.0.1'
    downloadPath: '.'

- task: CMake@1
  inputs:
    workingDirectory: 'frontends'
    cmakeArgs: '-G "Visual Studio 16 2019" -A x64 --config RelWithDebInfo -B build -D3DSMAX_VERSION=2019 .'
- task: CMake@1
  inputs:
    workingDirectory: 'frontends'
    cmakeArgs: '--build .\build --config RelWithDebInfo --target thunderloom_pattern_editor'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'frontends/release/'
    ArtifactName: 'build'
    publishLocation: 'Container'
