# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: DownloadPackage@1
  inputs:
    packageType: 'upack'
    feed: '/5f5d377c-f4e8-4587-acd2-348e71a79799'
    view: 
    definition: 'db2e8b61-26ce-4d06-8201-58f9e83232c9'
    version: '0.0.1'
    downloadPath: '$(System.ArtifactsDirectory)'
- task: DownloadPackage@1
  inputs:
    packageType: 'upack'
    feed: '/5f5d377c-f4e8-4587-acd2-348e71a79799'
    view: 
    definition: 'f25dc537-a23e-474d-98f3-fa5af32ce539'
    version: '0.0.1'
    downloadPath: '$(System.ArtifactsDirectory)'
- task: CMake@1
  inputs:
    workingDirectory: 'frontends'
    cmakeArgs: '-G "Visual Studio 16 2019" -A x64 --config RelWithDebInfo -B build -DCMAKE_INSTALL_PREFIX=install .'
